"""baseline existing schema

Revision ID: af76afcbe9b5
Revises: 
Create Date: 2026-08-20 23:02:46.868603
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af76afcbe9b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###